[build]
  command = "yarn run export"
  publish = "build"

# Plausible
[[redirects]]
  from = "/lava-cake/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
[[redirects]]
  from = "/lava-cake/api/event"
  to = "https://plausible.io/api/event"
  status = 200
